package com.cdel.advc.teacher.domain;

import java.io.Serializable;
import java.util.Date;

import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * Domain Object. Generated by RAD automatically.
 * 
 * @author zhangsulei
 */
public class TeacherStatistics extends BaseDomain implements Serializable {

	private static final long serialVersionUID = 4361081257487364602L;

	private Integer teacherID;
	private String teacherName;
	private String teacherCode;

	private Integer blackboardNewsNum;
	private Integer classActivityNum;
	private Integer replyMessageNum;
	private Integer replyReportRemarkNum;
	private Integer memberCallNum;
	private Integer memberCallSuccessNum;
	private Integer messageOTNum;
	private Integer reportRemarkOTNum;
	private Integer memberCallOTNum;

	private Date startDate;
	private Date endDate;

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getTeacherID() {
		return teacherID;
	}

	public void setTeacherID(Integer teacherID) {
		this.teacherID = teacherID;
	}

	public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public String getTeacherCode() {
		return teacherCode;
	}

	public void setTeacherCode(String teacherCode) {
		this.teacherCode = teacherCode;
	}

	public Integer getBlackboardNewsNum() {
		if (blackboardNewsNum == null) {
			blackboardNewsNum = 0;
		}
		return blackboardNewsNum;
	}

	public void setBlackboardNewsNum(Integer blackboardNewsNum) {
		this.blackboardNewsNum = blackboardNewsNum;
	}

	public Integer getClassActivityNum() {
		if (classActivityNum == null) {
			classActivityNum = 0;
		}
		return classActivityNum;
	}

	public void setClassActivityNum(Integer classActivityNum) {
		this.classActivityNum = classActivityNum;
	}

	public Integer getReplyMessageNum() {
		if (replyMessageNum == null) {
			replyMessageNum = 0;
		}
		return replyMessageNum;
	}

	public void setReplyMessageNum(Integer replyMessageNum) {
		this.replyMessageNum = replyMessageNum;
	}

	public Integer getReplyReportRemarkNum() {
		if (replyReportRemarkNum == null) {
			replyReportRemarkNum = 0;
		}
		return replyReportRemarkNum;
	}

	public void setReplyReportRemarkNum(Integer replyReportRemarkNum) {
		this.replyReportRemarkNum = replyReportRemarkNum;
	}

	public Integer getMemberCallNum() {
		if (memberCallNum == null) {
			memberCallNum = 0;
		}
		return memberCallNum;
	}

	public void setMemberCallNum(Integer memberCallNum) {
		this.memberCallNum = memberCallNum;
	}

	public Integer getMemberCallSuccessNum() {
		if (memberCallSuccessNum == null) {
			memberCallSuccessNum = 0;
		}
		return memberCallSuccessNum;
	}

	public void setMemberCallSuccessNum(Integer memberCallSuccessNum) {
		this.memberCallSuccessNum = memberCallSuccessNum;
	}

	public Integer getMessageOTNum() {
		if (messageOTNum == null) {
			messageOTNum = 0;
		}
		return messageOTNum;
	}

	public void setMessageOTNum(Integer messageOTNum) {
		this.messageOTNum = messageOTNum;
	}

	public Integer getReportRemarkOTNum() {
		if (reportRemarkOTNum == null) {
			reportRemarkOTNum = 0;
		}
		return reportRemarkOTNum;
	}

	public void setReportRemarkOTNum(Integer reportRemarkOTNum) {
		this.reportRemarkOTNum = reportRemarkOTNum;
	}

	public Integer getMemberCallOTNum() {
		if (memberCallOTNum == null) {
			memberCallOTNum = 0;
		}
		return memberCallOTNum;
	}

	public void setMemberCallOTNum(Integer memberCallOTNum) {
		this.memberCallOTNum = memberCallOTNum;
	}

}