package com.cdel.advc.website.domain;

import java.io.Serializable;
import java.util.Date;

import com.cdel.util.Contants;
import com.cdel.util.DESPlus;
import com.cdel.util.DateUtil;
import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * Domain Object. Generated by RAD automatically.
 * 
 * @version 1.0 2009-4-13
 * @author Arthur Liu - arthurliu@chinaacc.com
 */
@SuppressWarnings("serial")
public class Website extends BaseDomain implements Serializable {
	private Integer siteID;
	private String siteName;
	private Short status;
	private String domain;
	private Date createTime;
	private Integer creator;
	private String creatorName;
	private String courseAvgTimeUrl;
	private String userTimeUrl;
	private String selCourseUrl;
	private String chapterTimeUrl;
	private String phoneUrl;
	private String siteAttr;

	public Integer getSiteID() {
		return siteID;
	}

	public void setSiteID(Integer siteID) {
		this.siteID = siteID;
	}

	public String getSiteName() {
		return siteName;
	}

	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreator() {
		return creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public String getCourseAvgTimeUrl() {
		return courseAvgTimeUrl;
	}

	public void setCourseAvgTimeUrl(String courseAvgTimeUrl) {
		this.courseAvgTimeUrl = courseAvgTimeUrl;
	}

	public String getUserTimeUrl() {
		return userTimeUrl;
	}

	public void setUserTimeUrl(String userTimeUrl) {
		this.userTimeUrl = userTimeUrl;
	}

	public String getSelCourseUrl() {
		return selCourseUrl;
	}

	public void setSelCourseUrl(String selCourseUrl) {
		this.selCourseUrl = selCourseUrl;
	}

	public String getChapterTimeUrl() {
		return chapterTimeUrl;
	}

	public void setChapterTimeUrl(String chapterTimeUrl) {
		this.chapterTimeUrl = chapterTimeUrl;
	}

	public String getPhoneUrl() {
		return phoneUrl;
	}

	public void setPhoneUrl(String phoneUrl) {
		this.phoneUrl = phoneUrl;
	}

	public String getSiteAttr() {
		return siteAttr;
	}

	public void setSiteAttr(String siteAttr) {
		this.siteAttr = siteAttr;
	}

	public String getStatusStr() {
		if (status == null) {
			return "";
		} else {
			return Contants.status.get(status);
		}
	}

	public String getCreateTimeStr() {
		return DateUtil.getNowDateString(getCreateTime(), "yyyy-MM-dd");
	}

	public String getCreatorName() {
		return creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	public String getDecodeSiteAttr() throws Exception {
		if (siteAttr != null && !siteAttr.equals("")) {
			DESPlus des = new DESPlus();
			return des.decrypt(siteAttr);
		}
		return null;
	}

}