package com.cdel.qz.business.domain;

import java.io.Serializable;
import java.util.Date;

import com.cdel.util.Contants;
import com.cdel.util.DateUtil;
import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * Domain Object. Generated by RAD automatically. 专业
 * 
 * @author 张苏磊
 */
@SuppressWarnings("serial")
public class QzBusiness extends BaseDomain implements Serializable {
	private Integer businessID;
	private String businessName;
	private Short status;
	private Integer creator;
	private Date createTime;
	private String teacherName;
	private String createTimeStr;
	private Integer sequence;

	public Integer getBusinessID() {
		return businessID;
	}

	public void setBusinessID(Integer businessID) {
		this.businessID = businessID;
	}

	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Integer getCreator() {
		return creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getStatusStr() {
		if (status == null) {
			return "";
		} else {
			return Contants.status.get(status);
		}
	}

	public String getCreateTimeStr() {
		createTimeStr = DateUtil
				.getNowDateString(getCreateTime(), "yyyy-MM-dd");
		return createTimeStr;
	}

	public Integer getSequence() {
		return sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

}